version: '3'
services:
  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    depends_on:
      - consul
    restart: always

  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    restart: always

  registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: consul://consul:8500
    depends_on:
      - consul
      - registry
